# Based on https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
version: '{build}'

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda-x64

    - PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda36-x64

      
install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  #- set "PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Tools\\Scripts;%PATH%"
  - set "PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  #- set VCINSTALLDIR="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - set CL=-FI"%VCINSTALLDIR%\INCLUDE\stdint.h"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels wheeler-microfluidics
  - conda update -q conda
  - conda info -a
  - conda install --yes conda-build setuptools pip pytest-pylint parameterized cryptography
  - conda install --yes pycryptodomex scrypt pyyaml pytest pytest-mock coverage mock appdirs
  - conda install --yes ecdsa requests future websocket-client pytz six Click events prettytable pyinstaller


  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  #- "pip install --disable-pip-version-check --user --upgrade pip"
  #- "python -m pip install -U pip setuptools"
  #- "pip install --user pycrypto Paramiko"
  # - "pip install --user --upgrade graphenelib"

build_script:
  # Build the compiled extension
  - "python setup.py build"

test_script:
  # Run the project tests
  - "py.test tests/beembase"
  - "py.test tests/beemgraphene"

after_test:
  
  - ps: | # If tests are successful, create binary packages for the project.
      pyinstaller beempy-onedir.spec

  - ps: | # package artifacts
      copy /Y C:\OpenSSL-Win64\bin\libeay32.dll dist\beempy
      copy /Y C:\OpenSSL-Win64\bin\ssleay32.dll dist\beempy
      7z a beempy.zip %APPVEYOR_BUILD_FOLDER%\dist\beempy
      7z a -m0=LZMA2 -mx9 $env:BUILD %APPVEYOR_BUILD_FOLDER%\dist\beempy

  - ps: | # generate sha256 hashes
      (get-filehash $env:BUILD -algorithm SHA256).Hash | out-file ("{0}.sha256" -f $env:BUILD) -encoding ascii
      (get-filehash beempy.zip -algorithm SHA256).Hash | out-file "beempy.zip.sha256" -encoding ascii 
  

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: $(BUILD)
    name: beempy
  - path: $(BUILD).sha256
    name: beempy sha256 hash
  - path: beempy.zip
    name: beempy_zip
  - path: beempy.zip.sha256
    name: beempy_zip sha256 hash

on_finish: 
- ps: | # update appveyor build version, done last to prevent webhook breakage
    update-appveyorbuild -version $env:AVVER